package com.mycompany.graph;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 12;
  public static final int COLON = 5;
  public static final int EQUAL = 7;
  public static final int EOF = 0;
  public static final int ARROW = 4;
  public static final int ID = 11;
  public static final int COMMA = 8;
  public static final int DRAW = 2;
  public static final int error = 1;
  public static final int RPAREN = 10;
  public static final int SEMICOLON = 6;
  public static final int LPAREN = 9;
  public static final int PATH = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DRAW",
  "PATH",
  "ARROW",
  "COLON",
  "SEMICOLON",
  "EQUAL",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "ID",
  "NUM"
  };
}

